services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Kernel.php"

    App\Storage\Driver\:
        resource: "../src/Storage/Driver/*"
        tags: ["storage.driver"]

    App\Storage\StorageFactory:
        autoconfigure: true

    #
    # DBAL CONNECTION (source de vérité sharding)
    #
    Doctrine\DBAL\Connection:
        factory: ['Doctrine\DBAL\DriverManager', 'getConnection']
        arguments:
            -
                url: 'postgresql://root@cockroachdb:26257/defaultdb?sslmode=disable'
                driver: 'pdo_pgsql'

    #
    # Registry persistant
    #
    App\Sharding\Registry\DoctrineShardRegistry:
        arguments:
            $connection: '@Doctrine\DBAL\Connection'

    #
    # Interface → implementation
    #
    App\Sharding\Contract\ShardRegistryInterface:
        alias: App\Sharding\Registry\DoctrineShardRegistry